#!/bin/bash

set -e

boolean() {
  case $1 in
  true) echo true ;;
  false) echo false ;;
  *)
    echo "Err: Unknown boolean value \"$1\"" 1>&2
    exit 1
    ;;
  esac
}

# Get the VM external IP address
EXTERNAL_IP=$(curl -s http://whatismyip.akamai.com/)

# The script can either use `wget` or `curl` to pull other scripts
DOWNLOADER=

# Set installer mode
INSTALLER_DEBUG_MODE=$(boolean "${INSTALLER_DEBUG_MODE:-true}")

if $INSTALLER_DEBUG_MODE; then
  set +x
  REDIRECT=/dev/stdout
else
  REDIRECT=/dev/null
fi

# Helper functions
echo_success() {
  echo -e "\e[32m${1}\e[0m"
}

echo_bold() {
  echo -e "\e[1m${1}\e[0m"
}

fatal() {
  echo "$@" >&2
  exit 1
}

seperator() {
  yes = | head -n$(($(tput cols) * 1)) | tr -d '\n'
  printf "\n \n $($1 "$2") \n \n"
  yes = | head -n$(($(tput cols) * 1)) | tr -d '\n'
}

run_loading_animation() {
  i=1
  sp="/-\|"
  while :; do
    sleep 0.1
    # Don't show spinner when we are debugging
    if ! $INSTALLER_DEBUG_MODE; then
      printf "\b%s" ${sp:i++%${#sp}:1}
    fi
  done
}

does_command_exist() {
  command -v "$1" >/dev/null
}

verify_downloader() {
  # Return failure if it doesn't exist or is no executable
  does_command_exist "$1" || return 1

  # Set verified executable as our downloader program and return success
  DOWNLOADER=$1
  return 0
}

check_if_can_be_installed() {
  OS=$(uname | tr '[:upper:]' '[:lower:]')
  if [[ $OS != "linux" ]]; then
    fatal "Running this script is only supported on Linux systems."
  fi

  verify_downloader curl || verify_downloader wget || fatal 'Cannot find curl or wget for downloading files'
}

shell_config_file() {
 if [[ "${SHELL}" =~ zsh ]]; then
  SHELL_CONFIG_FILE="$HOME/.zshrc"
 elif [[ "${SHELL}" =~ bash ]]; then
  SHELL_CONFIG_FILE="$HOME/.bashrc"
 fi
}
install_python () {
    does_command_exist python && seperator echo_success "Python3 is already installed" ||
    apt install python3-pip && 
    seperator echo_success "Python3 has been installed"
}


check_if_can_be_installed 
does_command_exist pip


# python && 
# seperator echo_success "Python3 is already installed" ||
# seperator echo_bold "Python3 isn't installed"