#! bin/bash 


# Set debug mode
boolean() {
  case $1 in
  true) echo true ;;
  false) echo false ;;
  *)
    echo "Err: Unknown boolean value \"$1\"" 1>&2
    exit 1
    ;;
  esac
}

INSTALLER_DEBUG_MODE=$(boolean "${INSTALLER_DEBUG_MODE:-false}")

# Installer debug vars
if $INSTALLER_DEBUG_MODE; then
  set +x
  REDIRECT=/dev/stdout
  SUDO_REDIRECT="| sudo tee file"
else
  REDIRECT=/dev/null
fi

# Helper functions
echo_success() {
  echo -e "\e[32m${1}\e[0m"
}

echo_bold() {
  echo -e "\e[1m${1}\e[0m"
}

fatal() {
  echo "$@" >&2
  exit 1
}

seperator() {
  yes = | head -n$(($(tput cols) * 1)) | tr -d '\n'
  echo "\n \n $($1 "$2") \n \n"
  yes = | head -n$(($(tput cols) * 1)) | tr -d '\n'
}

# This is the easist way to add the Repo to your VM

download () {
  sudo apt update >${SUDO_REDIRECT} && sudo apt upgrade -y >${SUDO_REDIRECT} && sudo apt autoremove -y >${SUDO_REDIRECT} &&
  wget https://github.com/WCurtG/rasax-helm/archive/refs/heads/master.zip >${REDIRECT} &&
  sudo apt install unzip >${SUDO_REDIRECT} &&
  unzip master.zip >${REDIRECT}
}

clean () {
  find $HOME -type f -iname "master.zip" -mmin -2 -delete &&
  sleep 3 & echo_bold "Cleaning up your download...."
}

download &&
clean &&
seperator echo_success "master.zip has been cleaned from root and rasa-helm-master been added. You are currently in root/rasa-helm-master"