#! bin/bash 
# Helper functions
echo_success() {
  echo -e "\e[32m${1}\e[0m"
}

echo_bold() {
  echo -e "\e[1m${1}\e[0m"
}

fatal() {
  echo "$@" >&2
  exit 1
}

seperator() {
  yes = | head -n$(($(tput cols) * 1)) | tr -d '\n'
  printf "\n \n $($1 "$2") \n \n"
  yes = | head -n$(($(tput cols) * 1)) | tr -d '\n'
}
# This is the easist way to add the Repo to your VM

download () {
  sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y &&
  wget https://github.com/WCurtG/rasax-helm/archive/refs/heads/master.zip &&
  sudo apt install unzip &&
  unzip master.zip &&
  cd rasax-helm-master
  }

clean () {
  find $HOME -type f -iname "master.zip" -mmin -2 -delete &&
  sleep 3 & echo_bold "Cleaning up your download...."
}

download &&
clean &&
seperator echo_success "master.zip has been cleaned from root and rasa-helm-master been added. You are currently in root/rasa-helm-master" 
