#!/bin/bash

boolean() {
  case $1 in
  true) echo true ;;
  false) echo false ;;
  *)
    echo "Err: Unknown boolean value \"$1\"" 1>&2
    exit 1
    ;;
  esac
}

# Helper functions
EXTERNAL_IP=$(curl -s http://whatismyip.akamai.com/)

echo_success() {
  echo -e "\e[32m${1}\e[0m"
}

echo_bold() {
  echo -e "\e[1m${1}\e[0m"
}

fatal() {
  echo "$@" >&2
  exit 1
}

seperator() {
  yes = | head -n$(($(tput cols) * 1)) | tr -d '\n'
  printf "\n \n $($1 "$2") \n \n"
  yes = | head -n$(($(tput cols) * 1)) | tr -d '\n'
}

rebuild_kubectl_namespace() {
  cd $HOME &&
    kubectl delete namespace my-namespace &&
    kubectl create namespace my-namespace &&
    helm repo add rasa-x https://rasahq.github.io/rasa-x-helm &&
    helm --namespace my-namespace install --values values.yml my-release rasa-x/rasa-x
}

status () {
    k get services
    curl http://${EXTERNAL_IP}:8000/api/version
}


rebuild_kubectl_namespace && status &&
seperator echo_success "Your namespace has been rebuilt!" ||
seperator fatal "Something went wrong with your rebuild"