name: Intial Deployment of Rasa X to DigitalOcean droplet 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #   branches: [ master ]
#   pull_request:
#     branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Setting the workflow environment variables
env:
  DIGITALOCEAN_DROPLET: ${{ secrets.DIGITALOCEAN_DROPLET }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  REPO: ${GITHUB_REPOSITORY}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  params:
    name: params
    runs-on: ubuntu-latest
    # Map step outputs to job outputs, for use by downstream jobs
    outputs:
      git_branch: ${{ steps.git.outputs.git_branch }}
      git_repo: ${{ steps.git.outputs.git_repo }}

    steps:
      - name: git
        id: git
        run: |
          echo $GITHUB_REF
          git_branch=$(echo ${GITHUB_REF##*/})
          echo "::set-output name=git_branch::$git_branch"
          git_repo=$(echo ${GITHUB_REPOSITORY})
          echo "::set-output name=git_repo::$git_repo"


  params_summary:
    name: params_summary
    runs-on: ubuntu-latest
    needs: [params]
    steps:
    - name: params_summary
      run: |
        echo git_branch: ${{ needs.params.outputs.git_branch }}

  Auto_Deploy_Rasa_X:
    runs-on: ubuntu-latest
    needs: [params]
    steps:

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: SSH key set up
      shell: bash
      run: |
        mkdir ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa
    - name: Add droplet to the list of known hosts 
      run: |
        ssh-keyscan -H $(doctl compute droplet get "$DIGITALOCEAN_DROPLET" -o json |jq -r '.[]| "\(.networks.v4[1].ip_address)"') >> ~/.ssh/known_hosts
    - name: Download rasax-helm to exiting droplet     
      run: |
        echo $REPO
        doctl compute ssh "$DIGITALOCEAN_DROPLET" --ssh-command 'curl -s https://raw.githubusercontent.com/${{ steps.git.outputs.git_repo }}/${{ needs.params.outputs.git_branch }}/scripts/Install/download.sh | sudo bash &&
        rasax-helm/scripts/Install/./new_helm.sh'
