# This is a basic workflow to help you get started with Actions

name: SSH to DO

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Setting the workflow environment variables
env:
  DIGITALOCEAN_DROPLET: ${{ secrets.DIGITALOCEAN_DROPLET }}
  DIGITALOCEAN_SSH_KEY_NAME: ${{ secrets.DIGITALOCEAN_SSH_KEY_NAME }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into DigitalOcean Droplet
        run: |
          ssh -i "$DIGITALOCEAN_SSH_KEY_NAME" ubuntu@"$DIGITALOCEAN_DROPLET".digitalocean.com
          echo "Droplet is ready to use"
          cd $HOME
          touch GH_WAS_HERE.txt


