# This is a basic workflow to help you get started with Actions

name: doctl flow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Set-up  
    runs-on: ubuntu-latest
    steps: 

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: ssh in to DO droplet
      run: doctl compute ssh ${{ secrets.DIGITALOCEAN_DROPLET }} --ssh-key-path $GITHUB_WORKSPACE/.ssh

    - name: Run test command 
      run: echo "this is a test"  